#!/bin/bash

ROOT=$(cd $(dirname $0)/..; pwd)

function build {
    local BINARY
    BINARY=gh-models

    if [[ -n "${GOOS}" && -n "${GOARCH}" ]]; then
        BINARY=${BINARY}-${GOOS}-${GOARCH}
    fi

    if [ "${GOOS}" == "windows" ]; then
        BINARY=${BINARY}.exe
    fi

    echo "Building extension (GOOS=$GOOS GOARCH=$GOARCH)"
    echo "Output: ${BINARY}"

    go build -o ${ROOT}/${BINARY} ${ROOT}/main.go    
}

OS=$1

if [[ "$OS" == "windows" || "$OS" == "all" ]]; then
    GOOS=windows GOARCH=amd64 build
fi

if [[ "$OS" == "linux" || "$OS" == "all" ]]; then
    GOOS=linux GOARCH=amd64 build
    GOOS=android GOARCH=arm64 build
    GOOS=android GOARCH=amd64 build
fi

if [[ "$OS" == "darwin" || "$OS" == "all" ]]; then
    GOOS=darwin GOARCH=amd64 build
    GOOS=darwin GOARCH=arm64 build
fi

# Always build the "local" version, which defaults to the current OS/arch
build
